services:
  db:
    container_name: db-server
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/surbee/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: surbee
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    networks:
      - app-network
    healthcheck:
      test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 2s
      retries: 100

  backend:
    container_name: backend-server
    image: siyunp/surbee-springboot:1.0
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST : db
      SPRING_PROFILES_ACTIVE : private
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app-network

  mysqld-exporter:
    image: prom/mysqld-exporter
    volumes:
      - ./exporter/.my.cnf:/config/.my.cnf:ro
    command: ["--config.my-cnf=/config/.my.cnf"]
    ports:
      - "9104:9104"
    networks:
      - app-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - app-network

networks:
  app-network:
    driver: bridge